# https://github.com/marketplace/actions/azure-webapp#github-action-for-deploying-to-azure-web-app
name: Azure webapp CI CD

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build-and-deploy:
    environment: dev 
    runs-on: ubuntu-latest
    steps:
    # checkout the repo
    - name: 'Checkout Github Action'
      uses: actions/checkout@master
    - uses: azure/docker-login@v1
      with:
        login-server: ${{ secrets.REGISTRY_LOGIN }}
        username: ${{ secrets.REGISTRY_USERNAME }}
        password: ${{ secrets.REGISTRY_PASSWORD }}

    - run: |
        docker pull nginx:alpine
        docker tag nginx:alpine  ${{ secrets.REGISTRY_LOGIN }}/nginx:alpine 
        docker push ${{ secrets.REGISTRY_LOGIN }}/nginx:ok

    - uses: azure/webapps-deploy@v2
      with:
        app-name: 'salem-affes'
        publish-profile: ${{ secrets.azureWebAppPublishProfile }}
        images: ${{ secrets.REGISTRY_LOGIN }}/nginx:ok
