# https://github.com/marketplace/actions/azure-webapp#github-action-for-deploying-to-azure-web-app
name: Azure webapp CI CD

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build-and-deploy:
    environment: docker-hub 
    runs-on: ubuntu-latest
    steps:
      - name: 'Checkout Github Action'
        uses: actions/checkout@master
      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_TOKEN }}
      - name: Build and push Docker image
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          tags: lqss/portfolio:latest
      - name: Run web app
        uses: azure/webapps-deploy@v2
        with:
          app-name: 'salem-affes'
          publish-profile: ${{ secrets.AZUREWEBAPPPUBLISHPROFILE }}
          images: 'lqss/portfolio:latest'
