# https://github.com/marketplace/actions/azure-webapp#github-action-for-deploying-to-azure-web-app
name: Azure webapp CI CD

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build-and-deploy:
    environment: docker-hub 
    runs-on: ubuntu-latest
    steps:
    # checkout the repo
    - name: 'Checkout Github Action'
      uses: actions/checkout@master
    - name: Login to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKER_HUB_USERNAME }}
        password: ${{ secrets.DOCKER_HUB_TOKEN }}
    - run: |
        docker build . -t lqss/portfolio:latest
        docker push lqss/portfolio:latest 

    - uses: azure/webapps-deploy@v2
      with:
        app-name: 'salem-affes'
        publish-profile: ${{ secrets.azureWebAppPublishProfile }}
        images: 'lqss/portfolio:latest'
