# https://github.com/marketplace/actions/azure-webapp#github-action-for-deploying-to-azure-web-app
name: Azure webapp CI CD

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    # checkout the repo
    - name: 'Checkout Github Action'
      uses: actions/checkout@master

    - uses: azure/docker-login@v1
      with:
        login-server: lqss11.azurecr.io
        username: ${{ secrets.REGISTRY_USERNAME }}
        password: ${{ secrets.REGISTRY_PASSWORD }}

    - run: |
        docker build . -t contoso.azurecr.io/portfolio:${{ github.sha }}
        docker push lqss11.azurecr.io/portfolio:${{ github.sha }} 

    - uses: azure/webapps-deploy@v2
      with:
        app-name: 'salem-affes'
        publish-profile: ${{ secrets.azureWebAppPublishProfile }}
        images: 'lqss11.azurecr.io/portfolio:${{ github.sha }}'
